version: '3.8'
services:
  wechat_fastapi:
    build:
      context: .
      dockerfile: Dockerfile  # 指定Dockerfile的位置
    ports:
      - "80:4568"
    environment:
      - APP_PORT=4568
    volumes:
      - /root/logs:/logs